/* Mock data for the NADA messenger prototype */

const CHATS = [
  {
    id: "c1",
    name: "Echo",
    handle: "@echo.ghost",
    avatar: "av-3",
    initials: "EC",
    online: true,
    pinned: true,
    unread: 0,
    muted: false,
    lastActivity: "12:42",
    securityLevel: "verified",
    preview: "Voice note · 0:24",
    previewKind: "voice",
    typing: false,
  },
  {
    id: "c2",
    name: "Atlas Cell",
    handle: "@atlas.cell",
    avatar: "av-1",
    initials: "AC",
    online: true,
    pinned: true,
    unread: 3,
    muted: false,
    lastActivity: "12:38",
    securityLevel: "verified",
    preview: "Marek: ok we move at 21:00 sharp",
    previewKind: "text",
    typing: false,
    isGroup: true,
    members: 7,
  },
  {
    id: "c3",
    name: "Nova",
    handle: "@nova.0451",
    avatar: "av-2",
    initials: "NV",
    online: false,
    pinned: false,
    unread: 1,
    muted: false,
    lastActivity: "11:08",
    securityLevel: "verified",
    preview: "Sent you the keys. burn after read.",
    previewKind: "text",
    typing: false,
  },
  {
    id: "c4",
    name: "Wren",
    handle: "@wren.aleph",
    avatar: "av-4",
    initials: "WR",
    online: true,
    pinned: false,
    unread: 0,
    muted: false,
    lastActivity: "10:51",
    securityLevel: "verified",
    preview: "typing…",
    previewKind: "typing",
    typing: true,
  },
  {
    id: "c5",
    name: "Sable",
    handle: "@sable.ghost",
    avatar: "av-6",
    initials: "SB",
    online: false,
    pinned: false,
    unread: 0,
    muted: true,
    lastActivity: "Yesterday",
    securityLevel: "verified",
    preview: "📎 dossier.pdf",
    previewKind: "file",
    typing: false,
  },
  {
    id: "c6",
    name: "Kira",
    handle: "@kira.zero",
    avatar: "av-5",
    initials: "KI",
    online: false,
    pinned: false,
    unread: 0,
    muted: false,
    lastActivity: "Yesterday",
    securityLevel: "verified",
    preview: "You: see you tomorrow",
    previewKind: "self",
    typing: false,
  },
  {
    id: "c7",
    name: "Cipher Lab",
    handle: "group · 12 members",
    avatar: "av-7",
    initials: "CL",
    online: false,
    pinned: false,
    unread: 0,
    muted: true,
    lastActivity: "Mon",
    securityLevel: "verified",
    preview: "Doc: rotated the relay keys.",
    previewKind: "text",
    typing: false,
    isGroup: true,
    members: 12,
  },
  {
    id: "c8",
    name: "Lior",
    handle: "@lior.bare",
    avatar: "av-2",
    initials: "LI",
    online: false,
    pinned: false,
    unread: 0,
    muted: false,
    lastActivity: "Sun",
    securityLevel: "verified",
    preview: "🔒 vanish session ended",
    previewKind: "system",
    typing: false,
  },
];

/* Conversations — keyed by chat id */
const CONVERSATIONS = {
  c1: [
    { id: "m1", kind: "date", text: "Today" },
    { id: "m2", from: "them", type: "text", text: "you online?", time: "12:31", ghost: false },
    { id: "m3", from: "me",   type: "text", text: "yeah. just rotated keys. you good to talk?", time: "12:33", status: "read" },
    {
      id: "m4", from: "them", type: "text",
      text: "the relay you spun up last night — is it still hot?",
      time: "12:34", ghost: false,
    },
    {
      id: "m5", from: "me", type: "text",
      replyTo: { sender: "Echo", preview: "the relay you spun up last night — is it still hot?" },
      text: "yes. it's behind two hops now. nothing logs past the entry node.",
      time: "12:35", status: "read",
      reactions: [{ emoji: "🔥", count: 1, mine: false }],
    },
    {
      id: "m6", from: "them", type: "voice",
      duration: 24,
      time: "12:38",
      ghost: false,
      // 38-bar synthetic waveform; heights 0–1
      waveform: [0.28,0.45,0.62,0.38,0.74,0.92,0.55,0.41,0.68,0.30,0.55,0.78,0.60,0.34,0.46,0.82,0.95,0.70,0.52,0.40,0.62,0.48,0.30,0.55,0.80,0.92,0.66,0.42,0.55,0.30,0.48,0.70,0.85,0.58,0.42,0.30,0.40,0.55],
      played: 0.42,
    },
    {
      id: "m7", from: "me", type: "text",
      text: "got it. listening once and burning the cache.",
      time: "12:39", status: "read",
    },
    {
      id: "m8", from: "them", type: "text",
      text: "good. there's a meet tonight — sending the coords through Vault.",
      time: "12:40", ghost: true, vanishAt: "5m",
    },
    {
      id: "m9", from: "them", type: "file",
      fileName: "coords.enc", fileSize: "1.2 KB",
      time: "12:41", ghost: true, vanishAt: "5m",
    },
    {
      id: "m10", from: "me", type: "text",
      text: "received. on my way.",
      time: "12:42", status: "delivered",
      reactions: [{ emoji: "👻", count: 1, mine: false }, { emoji: "🫡", count: 2, mine: true }],
    },
  ],
};

const VAULT_ITEMS = [
  { id: "v1", name: "coords.enc",        size: "1.2 KB",  from: "Echo",      time: "12:41", icon: "file" },
  { id: "v2", name: "dossier.pdf",       size: "4.8 MB",  from: "Sable",     time: "Yesterday", icon: "file" },
  { id: "v3", name: "relay-keys.kdbx",   size: "82 KB",   from: "You",       time: "Yesterday", icon: "key"  },
  { id: "v4", name: "meet-2126.png",     size: "2.1 MB",  from: "Atlas Cell",time: "Mon",       icon: "image"},
  { id: "v5", name: "burner-roster.txt", size: "612 B",   from: "Nova",      time: "Mon",       icon: "file" },
];

Object.assign(window, { CHATS, CONVERSATIONS, VAULT_ITEMS });
